name: build-essence-mac

on:
  push

jobs:
  build:
    runs-on: macos-11
    timeout-minutes: 120
    steps:

      - name: checkout
        uses: actions/checkout@v2          

      - name: install dependencies
        run: brew install gcc@11 nasm ctags xz

      - name: build
        id: build
        run: git clone --depth=1 https://gitlab.com/nakst/essence.git && essence/util/automation/build_default.sh
        
      - name: upload
        id: upload       
        uses: actions/upload-artifact@v2
        with:
          name: debug-info
          path: essence
