
name: build-essence

on:
 schedule:
   - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:

      - name: checkout
        uses: actions/checkout@v2          

      - name: install dependencies
        run: |
          sudo apt-get install --no-install-recommends -y \
            ca-certificates \
            xz-utils        \
            texinfo         \
            patch           \
            make            \
            curl            \
            ctags           \
            m4              \
            nasm            \
            meson           \
            ninja-build     \
            qemu            \
            qemu-utils      \
            gcc             \
            g++
          pip install mako

      - name: build
        id: build
        run: git clone --depth=1 https://gitlab.com/nakst/essence.git && essence/util/automation/build.sh
        
      - name: release
        if: steps.build.outputs.RELEASE_NAME != ''
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.RELEASE_NAME }}
          release_name: ${{ steps.build.outputs.RELEASE_NAME }}
          body: |
            Essence automatically built from commit ${{ steps.build.outputs.COMMIT }}. Download and extract `Essence.tar.xz`. If you are using VirtualBox, import `Essence.ova`. If you are using Qemu, run `qemu-kvm -drive file=drive,format=raw -m 2048 -smp 2 || qemu-system-x86_64 -enable-kvm -drive file=drive,format=raw -m 2048 -smp 2`.

      - name: upload
        if: steps.build.outputs.RELEASE_NAME != ''
        id: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./${{ steps.build.outputs.OUTPUT_BINARY }}
          asset_name: Essence.tar.xz
          asset_content_type: application/x-compressed

      - name: upload_debug_info
        if: steps.build.outputs.RELEASE_NAME != ''
        id: upload_debug_info
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./${{ steps.build.outputs.DEBUG_OUTPUT_BINARY }}
          asset_name: _DebugInfo.tar.xz
          asset_content_type: application/x-compressed
